//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANAGER_TASK
    {
        public string Id_Task { get; set; }
        public string Id_User { get; set; }
        public Nullable<System.DateTime> Receive_Day { get; set; }
        public Nullable<System.DateTime> Deadline_Day { get; set; }
        public Nullable<System.DateTime> Finish_Day { get; set; }
    
        public virtual TASK TASK { get; set; }
        public virtual USER USER { get; set; }
    }
}
