//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.MANAGER_TASK = new HashSet<MANAGER_TASK>();
        }
    
        public string Id_Task { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Start_Day { get; set; }
        public Nullable<System.DateTime> Deadline_Day { get; set; }
        public Nullable<System.DateTime> Finish_Day { get; set; }
        public Nullable<int> Status_Now { get; set; }
        public string Id_Project { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANAGER_TASK> MANAGER_TASK { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
